version: "3.7"

services:
  postgres:
    image: "postgres:9.6"
    container_name: "postgres"
    restart: "always"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=mypassword
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 172.30.205.30
      KAFKA_CREATE_TOPICS: "test:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
  kafka-ui:
    image: provectuslabs/kafka-ui
    ports:
      - "3000:8080"
    environment:
      - KAFKA_CLUSTERS_0_NAME=172.30.205.30
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
      - KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper:2181